version: '3.8'

services:
  api:
    build:
      context: ./api/UrlShortener/UrlShortener
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=UrlShortener;Username=postgres;Password=password
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=UrlShortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d UrlShortener"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: